# Generated by Django 4.2.4 on 2023-08-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=255)),
                ('budget', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
